services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passcode
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services-net 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  sceneit:
    build: ./sceneit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - services-net
    volumes:
      - ./sceneit:/app
    command:
      sh -c "fastapi dev main.py"


networks:
  services-net:
    driver: bridge

volumes:
  pgdata:
    driver: local
